FROM alpine:latest

RUN apk add --no-cache --no-scripts yggdrasil coredns iptables iproute2 && \
    apk add --no-cache --no-scripts tayga --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]